import * as vscode from 'vscode';
import * as p from 'path';
import * as editFigure from '../editFigure';
import { insertSnippet } from './insertSnippet';

export class LatexSnippets{

	static async insertVectorFigure(editor: vscode.TextEditor, edit: vscode.TextEditorEdit, args: any[]){
	
		insertSnippet(editor, edit, args, (selection) => 
	`\\begin{figure}[ht]
		\\centering
		\\caption{}
		%\\incsvg{path/}{path/file}
		\\incsvg{${p.dirname(selection)}}{${selection}}\\\\
		\\label{fig:${p.parse(selection).name}}
	\\end{figure}`
		);
	
		editFigure.editVector(editor, edit, args);
	}
	
	static async insertBitmapFigure(editor: vscode.TextEditor, edit: vscode.TextEditorEdit, args: any[]){
		
		insertSnippet(editor, edit, args, (selection) => 
	`\\begin{figure}[ht]
		\\centering
		\\caption{}
		\\includegraphics[width=16cm]{${selection}.png}\\\\
		\\label{fig:${p.parse(selection).name}}
	\\end{figure}`
		);
		
		editFigure.editBitmap(editor, edit, args);
	}
	
	static async insertPre(editor: vscode.TextEditor, edit: vscode.TextEditorEdit, args: any[]){
	
		insertSnippet(editor, edit, args, () => 
	`% generated by the Super Figure vscode extension. May we stand on the shoulder's of giants\n
	\\usepackage{import}\n
	\\newcommand{\\incsvg}[2]{%\n
		\\def\\svgwidth{\\columnwidth}\n
		\\graphicspath{{#1}}\n
		\\input{#2.pdf_tex}\n
	}`
		);
	
	}
}

