# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json  
name: cicd

on:
  push:
    tags: [ "v**" ]
  
jobs:
  build:
    runs-on: node-20
    steps:
      - name: "Clone repo"
        uses: "actions/checkout@v3"

      - name: "Setup node"
        uses: "actions/setup-node@v3"
        with:
          node-version: 20

      - name: "Install dependencies"
        run: yarn install

      - name: "Compile and package"
        run: yarn vsce package -o "super-figure.vsix"

      - name: Save package artifact
        uses: "actions/upload-artifact@v3"
        with:
          name: "super-figure.vsix"
          path: "./super-figure.vsix"
  
  deploy-vscode-markplace:
    runs-on: node-20
    needs: 
      - build
    steps:
      - name: "Clone repo"
        uses: "actions/checkout@v3"

      - name: Install vsce
        run: yarn global add @vscode/vsce

      - name: "Get package artifact"
        uses: "actions/download-artifact@v3"
        with:
          name: "super-figure.vsix"

      # https://code.visualstudio.com/api/working-with-extensions/publishing-extension
      - name: "Publish package to Vscode Marketplace"
        env:
          VSC_PAT: ${{ secrets.VSC_PAT }}
        run: vsce publish -p "$VSC_PAT" -i "super-figure.vsix/super-figure.vsix"

  deploy-open-vsx:
    runs-on: node-20
    needs: 
      - build
    steps:
      - name: "Clone repo"
        uses: "actions/checkout@v3"

      - name: Install vsce
        run: yarn global add ovsx

      - name: "Get package artifact"
        uses: "actions/download-artifact@v3"
        with:
          name: "super-figure.vsix"

      # https://github.com/eclipse/openvsx/wiki/Publishing-Extensions#1-create-an-access-token 
      - name: "Publish package to OpenVSX Registry"
        env:
          OVSX_PAT: ${{ secrets.OVSX_PAT }}
        run: yarn ovsx publish -p "$OVSX_PAT" -i "super-figure.vsix/super-figure.vsix"


  # release:
  #   needs: [ build ]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: "Get package artifact"
  #       uses: "actions/download-artifact@v3"
  #       with:
  #         name: "super-figure.vsix"

  #     - name: "Gitea release"
  #       uses: "https://github.com/ncipollo/release-action@v1"
  #       with:
  #         name: ${{ needs.build.outputs.packagename }}
  #         artifacts: "super-figure.vsix"