name: cicd

on:
  push:
    branches: [master]
    # only on v.x.x.x versions 
    tags: [ "v.**" ]
  
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    outputs:
      packagename: ${{ steps.package.outputs.packagename }}
    steps:
      - name: "Clone repo"
        uses: "actions/checkout@v3"

      - name: "Setup node"
        uses: "actions/setup-node@v3"
        with:
          node-version: 16

      - name: "Build"
        run: "yarn install"

      - name: "Package"
        run: "yarn vsce package"

      - name: "Package name"
        id: package
        run: "find *.vsix"

      - name: Save package artifact
        uses: "actions/upload-artifact@v3"
        with:
          name: "super-figure.vsix"
          path: "*.vsix"

      # https://code.visualstudio.com/api/working-with-extensions/publishing-extension
      - name: "Publish package to Vscode Marketplace"
        run: "yarn vsce publish -p ${{ gitea.secrets.VSC_PAT }}"

      # https://github.com/eclipse/openvsx/wiki/Publishing-Extensions#1-create-an-access-token 
      - name: "Publish package to OpenVSX Registry"
        run: "yarn ovsx publish -p ${{ gitea.secrets.OVSX_PAT }}"


  # release:
  #   needs: [ build ]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: "Get package artifact"
  #       uses: "actions/download-artifact@v3"
  #       with:
  #         name: "super-figure.vsix"

  #     - name: "Gitea release"
  #       uses: "https://github.com/ncipollo/release-action@v1"
  #       with:
  #         name: ${{ needs.build.outputs.packagename }}
  #         artifacts: "super-figure.vsix"